#pragma once

typedef enum
{
    PRIMITIVE_POINTS = 0,
    PRIMITIVE_LINES,
    PRIMITIVE_LINE_STRIP,
    PRIMITIVE_LINE_LOOP,
    PRIMITIVE_TRIANGLES,
    PRIMITIVE_TRIANGLE_STRIP,
    PRIMITIVE_TRIANGLE_FAN,
    PRIMITIVE_QUADS,
    PRIMITIVE_QUAD_STRIP,
    PRIMITIVE_POLYGON,

    PRIMITIVE_ANY  // not for user
} Primitive;

